# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 667c1bff6d0b1f6ca8af92dc3a8d1109b3574cb98674fac93fb08d6b972a97d72af1ade49aab701cbc9ee1da471c21bccab604f3b3e0491b808dc36e46f05b27

test:
  secret_key_base: e4f58de59207c1a25086e1304aba5c232c9c8d7abc1dd18e734fe7393276b93c14c7ab1a3202ba24f8d7b6fd9aadf7ad2097f9688e68d3f6be4fcc659830a849

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
